type AlreadyExistingNoteException* = object of CatchableError
